services:
  crypto-tgbot:
    build: .
    restart: always
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD: postgres
      - POSTGRES_USER: postgres
      - POSTGRES_DB: coinglass
    volumes:
      - ./db:/var/lib/postgresql/data
    expose:
      - 5432
    