services:
  crypto-tgbot:
    container_name: coinglass_bot
    build: .
    restart: always
    depends_on:
      - database
  database:
    container_name: coinglass_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    volumes:
      - ./db:/var/lib/postgresql/data
    expose:
      - 5432
    