// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	domain "crypto-exchange/exchange/domain"

	mock "github.com/stretchr/testify/mock"
)

// PairUsecase is an autogenerated mock type for the PairUsecase type
type PairUsecase struct {
	mock.Mock
}

// AddFundingSearched provides a mock function with given fields: chatID, exchange, symbol
func (_m *PairUsecase) AddFundingSearched(chatID int64, exchange string, symbol string) error {
	ret := _m.Called(chatID, exchange, symbol)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, string, string) error); ok {
		r0 = rf(chatID, exchange, symbol)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetFundingData provides a mock function with given fields: exchange, symbol
func (_m *PairUsecase) GetFundingData(exchange string, symbol string) (domain.FundingData, error) {
	ret := _m.Called(exchange, symbol)

	var r0 domain.FundingData
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (domain.FundingData, error)); ok {
		return rf(exchange, symbol)
	}
	if rf, ok := ret.Get(0).(func(string, string) domain.FundingData); ok {
		r0 = rf(exchange, symbol)
	} else {
		r0 = ret.Get(0).(domain.FundingData)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(exchange, symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFundingDataOfUser provides a mock function with given fields: chatID
func (_m *PairUsecase) GetFundingDataOfUser(chatID int64) ([]domain.FundingData, error) {
	ret := _m.Called(chatID)

	var r0 []domain.FundingData
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]domain.FundingData, error)); ok {
		return rf(chatID)
	}
	if rf, ok := ret.Get(0).(func(int64) []domain.FundingData); ok {
		r0 = rf(chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.FundingData)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFundingNotification provides a mock function with given fields: chatID
func (_m *PairUsecase) GetFundingNotification(chatID int64) ([]domain.FundingNotification, error) {
	ret := _m.Called(chatID)

	var r0 []domain.FundingNotification
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]domain.FundingNotification, error)); ok {
		return rf(chatID)
	}
	if rf, ok := ret.Get(0).(func(int64) []domain.FundingNotification); ok {
		r0 = rf(chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.FundingNotification)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastFiveFundingSearched provides a mock function with given fields: chatID
func (_m *PairUsecase) GetLastFiveFundingSearched(chatID int64) ([]domain.Pair, error) {
	ret := _m.Called(chatID)

	var r0 []domain.Pair
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]domain.Pair, error)); ok {
		return rf(chatID)
	}
	if rf, ok := ret.Get(0).(func(int64) []domain.Pair); ok {
		r0 = rf(chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Pair)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPerpData provides a mock function with given fields: exchange, symbol
func (_m *PairUsecase) GetPerpData(exchange string, symbol string) (domain.PerpData, error) {
	ret := _m.Called(exchange, symbol)

	var r0 domain.PerpData
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (domain.PerpData, error)); ok {
		return rf(exchange, symbol)
	}
	if rf, ok := ret.Get(0).(func(string, string) domain.PerpData); ok {
		r0 = rf(exchange, symbol)
	} else {
		r0 = ret.Get(0).(domain.PerpData)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(exchange, symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPairUsecase creates a new instance of PairUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPairUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *PairUsecase {
	mock := &PairUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
