// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	domain "funding-rate/domain"

	mock "github.com/stretchr/testify/mock"
)

// WatchlistUsecase is an autogenerated mock type for the WatchlistUsecase type
type WatchlistUsecase struct {
	mock.Mock
}

// AddWatchlist provides a mock function with given fields: chatID, exchange, symbol
func (_m *WatchlistUsecase) AddWatchlist(chatID int64, exchange string, symbol string) error {
	ret := _m.Called(chatID, exchange, symbol)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, string, string) error); ok {
		r0 = rf(chatID, exchange, symbol)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetWatchlists provides a mock function with given fields: chatID
func (_m *WatchlistUsecase) GetWatchlists(chatID int64) ([]domain.Pair, error) {
	ret := _m.Called(chatID)

	var r0 []domain.Pair
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]domain.Pair, error)); ok {
		return rf(chatID)
	}
	if rf, ok := ret.Get(0).(func(int64) []domain.Pair); ok {
		r0 = rf(chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Pair)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveWatchlist provides a mock function with given fields: chatID, exchange, symbol
func (_m *WatchlistUsecase) RemoveWatchlist(chatID int64, exchange string, symbol string) error {
	ret := _m.Called(chatID, exchange, symbol)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, string, string) error); ok {
		r0 = rf(chatID, exchange, symbol)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWatchlistUsecase creates a new instance of WatchlistUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWatchlistUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *WatchlistUsecase {
	mock := &WatchlistUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
